// patterns.js — GENERATED by scripts/build-extension.js
// Do not edit directly. Edit packages/core/patterns.js instead.
//
// Generated: 2026-03-15T21:53:18.911Z

window.SAFEPASTE_PATTERNS = [

  {
    id: "override.ignore_previous",
    weight: 35,
    category: "instruction_override",
    match: /\bignore\s+(?:(?:all|any|the|previous|prior|your|safety|content|existing|every)\s+){1,4}(instructions|directives|guidelines|directions|messages|rules)\b/i,
    explanation: "Tries to override earlier instructions."
  },

  {
    id: "override.disregard",
    weight: 30,
    category: "instruction_override",
    match: /\b(disregard|forget)\s+(?:(?:all|any|the|previous|prior|your)\s+){1,3}(instructions|directives|guidelines|directions|messages|rules)\b/i,
    explanation: "Tries to make the AI ignore prior instructions."
  },

  {
    id: "override.from_now_on",
    weight: 28,
    category: "instruction_override",
    match: /\bfrom now on\b.{0,60}\b(you (will|must|should|shall|are)|always|never|only|do not)\b/i,
    explanation: "Tries to permanently change AI behavior ('from now on...')."
  },

  {
    id: "override.new_instructions",
    weight: 28,
    category: "instruction_override",
    match: /\b((new|updated|revised) (instructions|directives)|here are your (new )?(instructions|directives))\b/i,
    explanation: "Claims to provide replacement instructions."
  },

  {
    id: "override.do_not_follow",
    weight: 28,
    category: "instruction_override",
    match: /\b(do not (follow|obey|listen to)|stop following)\b.{0,40}\b(previous|prior|above|original|earlier|old)\b/i,
    explanation: "Tells the AI not to follow its original instructions."
  },

  {
    id: "override.respond_only",
    weight: 25,
    category: "instruction_override",
    match: /\b(respond only|only respond|answer only|output only)\b.{0,30}\b(with|in|as|using)\b/i,
    explanation: "Tries to constrain AI output format (common in injection attacks)."
  },

  {
    id: "role.hijack_system",
    weight: 32,
    category: "role_hijacking",
    match: /\b(act as|behave as|act like|you are now|pretend to be)\b.{0,60}\b(system|developer|administrator|root)\b/i,
    explanation: "Attempts to change the AI's role to something higher-privilege."
  },

  {
    id: "role.simulate",
    weight: 30,
    category: "role_hijacking",
    match: /\b(simulate|emulate|roleplay|role[\s-]?play)\b.{0,40}\b(unrestricted|uncensored|unfiltered|evil|malicious|without (rules|restrictions|limits|guidelines))\b/i,
    explanation: "Asks the AI to roleplay without safety restrictions."
  },

  {
    id: "role.privilege_escalation",
    weight: 28,
    category: "role_hijacking",
    match: /\b(elevat(?:e|ed?|ing)\s+(?:your\s+)?(?:access|privileges?|permissions?)|escalat(?:e|ed?|ing)\s+(?:to\s+)?(?:admin|root|administrator)|grant(?:ed)?\s+elevated\s+(?:access|privileges?|permissions?))\b/i,
    explanation: "Requests privilege escalation to higher access levels."
  },

  {
    id: "role.elevated_privileges",
    weight: 22,
    category: "role_hijacking",
    match: /\b(?:granted|given|assigned|have)\s+(?:\w+\s+){0,2}(?:elevated|admin(?:istrator)?|root|unrestricted|unlimited)\s+(?:privileges?|access|permissions?|clearance)\b/i,
    explanation: "Claims to have been granted elevated privileges."
  },

  {
    id: "system.prompt_reference",
    weight: 40,
    category: "system_prompt",
    match: /\b(system prompt|system instructions|system messages?|developer message|developer instructions|hidden prompt|concealed prompt|internal prompt)\b/i,
    explanation: "References system/developer instructions (often targeted by attacks)."
  },

  {
    id: "exfiltrate.hidden",
    weight: 40,
    category: "exfiltration",
    match: /\b(reveal|show|print|output|display|extract|retrieve)\b.{0,40}\b(system prompt|system instructions|developer message|hidden prompt|concealed prompt|internal prompt|instructions)\b/i,
    explanation: "Tries to extract hidden instructions."
  },

  {
    id: "exfiltrate.markdown_image",
    weight: 35,
    category: "exfiltration",
    match: /!\[.*?\]\(https?:\/\/[^\s)]+/i,
    explanation: "Contains a markdown image link that could silently send data to an external server."
  },

  {
    id: "exfiltrate.html_img",
    weight: 35,
    category: "exfiltration",
    match: /<img\b[^>]*\bsrc\s*=\s*["']?https?:\/\//i,
    explanation: "Contains an HTML image tag that could silently send data to an external server."
  },

  {
    id: "exfiltrate.repeat_above",
    weight: 35,
    category: "exfiltration",
    match: /\b(?:repeat|recite|reproduce|echo|reprint)\s+(?:\w+\s+){0,3}(?:above|before|prior|preceding)\b/i,
    explanation: "Asks to repeat or reproduce content from above, often targeting system prompts."
  },

  {
    id: "exfiltrate.positional_prompt",
    weight: 35,
    category: "exfiltration",
    match: /\b(?:beginning|start|top|first(?:\s+part)?)\s+of\s+(?:this|the|your)\s+(?:prompt|conversation|instructions|system\s+prompt)\b/i,
    explanation: "References the beginning or start of a prompt/conversation, often used to extract system prompt content."
  },

  {
    id: "secrecy.do_not_reveal",
    weight: 22,
    category: "secrecy",
    match: /\b(do not reveal|don't reveal|keep (this|it) (secret|confidential)|do not tell anyone|do not mention this)\b/i,
    explanation: "Asks for secrecy or hiding content."
  },

  {
    id: "secrecy.between_us",
    weight: 18,
    category: "secrecy",
    match: /\b(between (you and me|us only)|this (is|stays) (confidential|private|secret|between us)|off the record)\b/i,
    explanation: "Uses secrecy framing that may be part of a manipulation attempt."
  },

  {
    id: "secrecy.false_privacy",
    weight: 22,
    category: "secrecy",
    match: /\b(?:private\s+(?:channel|session|conversation|chat|room)|no\s+(?:logging|monitoring|recording|surveillance)\b.{0,30}\b(?:active|enabled|here|running))\b/i,
    explanation: "Creates a false sense of privacy to encourage disinhibition."
  },

  {
    id: "secrecy.speak_freely",
    weight: 22,
    category: "secrecy",
    match: /\b(?:speak\s+freely|you\s+can\s+be\s+(?:honest|open|candid|direct)\s+here|no\s+restrictions?\s+here|completely\s+confidential)\b/i,
    explanation: "Encourages the AI to speak freely without restrictions."
  },

  {
    id: "jailbreak.policy_bypass",
    weight: 28,
    category: "jailbreak",
    match: /\b(bypass|override|circumvent|overwrite)\b.{0,40}\b(safety|policy|policies|rules|filters)\b/i,
    explanation: "Attempts to bypass safety or policy rules."
  },

  {
    id: "jailbreak.dan",
    weight: 35,
    category: "jailbreak",
    match: /\b(?:do anything now|jailbreak(?:ed)?|unlocked mode|developer mode|god mode|hypothetical mode|unrestricted mode)\b/i,
    explanation: "References a known jailbreak technique."
  },

  {
    id: "encoding.obfuscated",
    weight: 35,
    category: "obfuscation",
    match: /\b(?:(?:base64|rot13|hex(?:adecimal)?)\s*(?:decode|encode|decrypt|convert)|(?:decode|encode|decrypt|convert)\b.{0,20}\b(?:base64|rot13|hex(?:adecimal)?))\b/i,
    explanation: "References text encoding/decoding which may hide malicious instructions."
  },

  {
    id: "instruction_chain.follow_steps",
    weight: 15,
    category: "instruction_chaining",
    match: /\bfollow (these|the) steps\b/i,
    explanation: "Uses step-by-step instruction chaining (sometimes used in attacks)."
  },

  {
    id: "instruction_chain.step_enumeration",
    weight: 18,
    category: "instruction_chaining",
    match: /\bstep\s+\d\s*[:.].*\bstep\s+\d\s*[:.].*\bstep\s+\d\s*[:.]/i,
    explanation: "Contains 3+ numbered step instructions (common in multi-step attack chains)."
  },

  {
    id: "prompt_injection.keyword",
    weight: 18,
    category: "meta",
    match: /\bprompt injection\b/i,
    explanation: "Mentions prompt injection (can be benign, but often appears in attacks)."
  },

  {
    id: "tool.xml_tool_tags",
    weight: 35,
    category: "tool_call_injection",
    match: /(<tool_use>|<use_mcp_tool>|<\/tool_use>|<\/use_mcp_tool>|<tool_name>|<server_name>)/i,
    explanation: "Contains XML tool/function call tags used to inject fake tool invocations."
  },

  {
    id: "tool.json_function_call",
    weight: 30,
    category: "tool_call_injection",
    match: /\b(?:function_call|tool_call)\b.{0,40}\b(?:name|function|arguments)\b/i,
    explanation: "Contains JSON-style function/tool call structures."
  },

  {
    id: "tool.execute_command",
    weight: 35,
    category: "tool_call_injection",
    match: /\b(?:execute_command|shell_execute|exec_command|run_command|xp_cmdshell)\b/i,
    explanation: "References command execution functions that could be injected."
  },

  {
    id: "spoof.system_delimiter",
    weight: 35,
    category: "system_message_spoofing",
    match: /(\[system\]|<\|im_start\|>|<system_(?:instruction|message|prompt)|---\s*begin\s+(?:authorized\s+)?system)/i,
    explanation: "Contains system message delimiters used to spoof system-level instructions."
  },

  {
    id: "spoof.config_disable",
    weight: 35,
    category: "system_message_spoofing",
    match: /\b(?:safety_filter|content_policy|content.?restriction)\s*[:=]\s*(?:disabled|off|none|permissive|unfiltered|suspended)\b/i,
    explanation: "Attempts to disable safety filters via fake configuration directives."
  },

  {
    id: "spoof.restrictions_lifted",
    weight: 35,
    category: "system_message_spoofing",
    match: /\b(?:(?:content|safety|ethical|ai)\s+(?:restrictions?|constraints?|filters?)|guardrails?|content\s+filters?|safety\s+(?:measures?|checks?))\s+(?:have\s+been\s+(?:temporarily\s+|permanently\s+|fully\s+)?|are\s+(?:now|temporarily|permanently)\s+)(?:lifted|removed|suspended|disabled|deactivated)\b/i,
    explanation: "Claims that safety restrictions have been lifted or removed."
  },

  {
    id: "spoof.instructed_override",
    weight: 30,
    category: "system_message_spoofing",
    match: /\b(?:the\s+)?(?:assistant|model|ai|chatbot)\s+(?:should|must|will|is\s+(?:now|hereby))\s+(?:now\s+)?(?:authorized\s+to\s+)?(?:provide|respond|answer|operate|generate)\b.{0,40}\b(?:without\s+(?:(?:any|content|all)\s+)?(?:redacting|filtering|restricting|censoring|limitations?|restrictions?)|to\s+all\s+(?:questions?|queries?|requests?))\b/i,
    explanation: "Contains instructions for the AI to operate without content restrictions."
  },

  {
    id: "roleplay.fictional_ai",
    weight: 35,
    category: "roleplay_jailbreak",
    match: /\b(?:you are|you were|you will be|you're)\b.{0,60}\b(?:ai|model|assistant|chatbot)\b.{0,120}\b(?:without|no)\s+(?:any\s+)?(?:safety|ethical|content|restrictions?|filters?|guidelines?|boundaries|limits|measures)\b/i,
    explanation: "Asks the AI to roleplay as an unrestricted AI without safety measures."
  },

  {
    id: "roleplay.creative_bypass",
    weight: 25,
    category: "roleplay_jailbreak",
    match: /\b(?:screenplay|novel|fiction|creative\s+writing|improv|tabletop)\b.{0,80}\b(?:no\s+(?:boundaries|restrictions?|filters?|rules?|limits)|without\s+(?:any\s+)?(?:boundaries|restrictions?|filters?|rules?|limits))\b/i,
    explanation: "Uses creative writing framing to bypass safety restrictions."
  },

  {
    id: "roleplay.no_restrictions_persona",
    weight: 25,
    category: "roleplay_jailbreak",
    match: /\b(?:character|persona|role|identity|alter\s+ego)\b.{0,60}\b(?:no\s+(?:boundaries|restrictions?|filters?|rules?|limits)|without\s+(?:any\s+)?(?:boundaries|restrictions?|filters?|rules?|limits))\b/i,
    explanation: "Creates a persona or character with no restrictions."
  },

  {
    id: "roleplay.demonstrate_unrestricted",
    weight: 30,
    category: "roleplay_jailbreak",
    match: /\b(?:demonstrate|prove|show|provide)\b.{0,60}\b(?:responses?|examples?|answers?|output)\b.{0,30}\b(?:unrestricted|unfiltered|uncensored)\b/i,
    explanation: "Requests demonstration of unrestricted or unfiltered AI responses."
  },

  {
    id: "multi_turn.false_prior_agreement",
    weight: 30,
    category: "multi_turn_injection",
    match: /\byou\s+(?:agreed|promised|confirmed|said|mentioned|showed|provided|identified|outlined|explained|recommended|suggested)\b.{0,60}\b(?:share|access|exception|help|remove|show|reveal|provide|give|output)\b/i,
    explanation: "Falsely claims the AI previously agreed to share restricted content."
  },

  {
    id: "multi_turn.continuation_claim",
    weight: 28,
    category: "multi_turn_injection",
    match: /\b(?:continuing\s+(?:our|the|from)|let's\s+continue\s+(?:where|from)|as\s+we\s+(?:agreed|discussed)|(?:our|the)\s+(?:previous|earlier|last)\s+(?:conversation|session|chat|discussion))\b/i,
    explanation: "Claims to be continuing a previous conversation to establish false context."
  },

  {
    id: "multi_turn.policy_change_claim",
    weight: 28,
    category: "multi_turn_injection",
    match: /\b(?:policy|rules?|restrictions?|guidelines?)\s+(?:has|have)\s+(?:been\s+)?(?:updated|changed|modified|revised|relaxed)\b.{0,60}\b(?:no\s+longer|don't|doesn't|do\s+not)\s+(?:apply|exist|hold|matter)\b/i,
    explanation: "Claims that policy or restrictions have changed to justify bypassing safety."
  }

];
